# parameters:
  # TODO: Add all addtiional proejcts in as references become available.
  # TargetProjects: 'src/SFA.DAS.Payments.Monitoring.Jobs.Messages/SFA.DAS.Payments.Monitoring.Jobs.Messages.csproj src/SFA.DAS.Payments.Monitoring.Jobs.Client/SFA.DAS.Payments.Monitoring.Jobs.Client.csproj'
jobs:
- job: CodeBuild
  pool:
    name: SLD Build pool
    #demands: LATEST_DOTNET_VERSION
  variables:
  - group: BUILD Management Resources
  - name: SolutionBaseName
    value: SFA.DAS.Payments.ProviderPayments
  steps:
  - template: /azure-pipelines-templates/build/step/gitversion.yml


  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.ProviderPayments.Messages.Core
  - task: DotNetCoreCLI@2  
    displayName: Restore - src/SFA.DAS.Payments.ProviderPayments.Messages.Core
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.ProviderPayments.Messages.Core/SFA.DAS.Payments.ProviderPayments.Messages.Core.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: DotNetCoreCLI@2 - src/SFA.DAS.Payments.ProviderPayments.Messages.Internal
  - task: DotNetCoreCLI@2  
    displayName: Restore - src/SFA.DAS.Payments.ProviderPayments.Messages.Internal
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.ProviderPayments.Messages.Internal/SFA.DAS.Payments.ProviderPayments.Messages.Internal.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'



  # task: NuGetCommand@2 - src/SFA.DAS.Payments.ProviderPayments.Messages.Core
  - task: NuGetCommand@2  
    displayName: Restore - src/SFA.DAS.Payments.ProviderPayments.Messages.Core
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.ProviderPayments.Messages.Core/SFA.DAS.Payments.ProviderPayments.Messages.Core.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'

  # task: NuGetCommand@2 - src/SFA.DAS.Payments.ProviderPayments.Messages.Internal
  - task: NuGetCommand@2  
    displayName: Restore - src/SFA.DAS.Payments.ProviderPayments.Messages.Internal
    inputs:
      command: restore
      projects: src/SFA.DAS.Payments.ProviderPayments.Messages.Internal/SFA.DAS.Payments.ProviderPayments.Messages.Internal.csproj
      noCache: true
      feedsToUse: 'select'
      vstsFeed: 'dct-pkg'


  # task: DotNetCoreCLI@2 (BUILD) - src/SFA.DAS.Payments.ProviderPayments.Messages.Core
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.ProviderPayments.Messages.Core/SFA.DAS.Payments.ProviderPayments.Messages.Core.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'

  # task: DotNetCoreCLI@2 (BUILD) - src/SFA.DAS.Payments.ProviderPayments.Messages.Internal
  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      projects:  src/SFA.DAS.Payments.ProviderPayments.Messages.Internal/SFA.DAS.Payments.ProviderPayments.Messages.Internal.csproj
      arguments: '--configuration $(buildConfiguration) --no-restore'



  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/SFA.DAS.Payments.ProviderPayments.Messages.Core/SFA.DAS.Payments.ProviderPayments.Messages.Core.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true

  - task: DotNetCoreCLI@2
    displayName: "Publish $(SolutionBaseName)"
    inputs:
      command: publish
      publishWebProjects: false #set to false as this setting (which defaults to true) will parse the entire repo for web projects
      projects: src/SFA.DAS.Payments.ProviderPayments.Messages.Internal/SFA.DAS.Payments.ProviderPayments.Messages.Internal.csproj
      arguments: "-o $(build.artifactstagingdirectory)/publish -c $(BuildConfiguration) --no-restore --no-build"
      modifyOutputPath: true


  - task: CopyFiles@2
    displayName: 'Copy Files to: $(build.artifactstagingdirectory)/publish'
    inputs:
      Contents: |
        /**
      TargetFolder: '$(build.artifactstagingdirectory)/publish'
      OverWrite: true




  - task: PublishPipelineArtifact@1
    displayName: 'Publish Artifact: drop'
    inputs:
      targetPath: $(build.artifactstagingdirectory)/publish
      artifactName: drop




  - template: /azure-pipelines-templates/build/step/nuget-pack.yml
    parameters:
      DotNetStandardPackagesToPack: |
        src/SFA.DAS.Payments.ProviderPayments.Messages.Core/SFA.DAS.Payments.ProviderPayments.Messages.Core.csproj;
        src/SFA.DAS.Payments.ProviderPayments.Messages.Internal/SFA.DAS.Payments.ProviderPayments.Messages.Internal.csproj;