// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SFA.DAS.Payments.ProviderPayments.AcceptanceTests.MonthEnd
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Month End")]
    public partial class MonthEndFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "Month End.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Month End", "Month End", "\tAs a Provider \r\n\tI would like to receive payments calculated after the period cl" +
                    "oses", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 5
#line hidden
#line 6
 testRunner.Given("a learner is undertaking a training with a training provider", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 7
 testRunner.And("the SFA contribution percentage is 90%", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Provider payments after month end")]
        public void ProviderPaymentsAfterMonthEnd()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Provider payments after month end", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 9
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 5
this.FeatureBackground();
#line hidden
#line 10
 testRunner.Given("the current collection period is R02", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 11
 testRunner.And("the payments are for the current collection year", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "Delivery Period",
                            "Transaction Type",
                            "Funding Source",
                            "Amount"});
                table7.AddRow(new string[] {
                            "1",
                            "Learning (TT1)",
                            "CoInvestedSfa",
                            "900"});
                table7.AddRow(new string[] {
                            "1",
                            "Completion (TT2)",
                            "CoInvestedSfa",
                            "2700"});
                table7.AddRow(new string[] {
                            "1",
                            "Balancing (TT3)",
                            "CoInvestedSfa",
                            "1800"});
                table7.AddRow(new string[] {
                            "1",
                            "Learning (TT1)",
                            "CoInvestedEmployer",
                            "100"});
                table7.AddRow(new string[] {
                            "1",
                            "Completion (TT2)",
                            "CoInvestedEmployer",
                            "300"});
                table7.AddRow(new string[] {
                            "1",
                            "Balancing (TT3)",
                            "CoInvestedEmployer",
                            "1350"});
                table7.AddRow(new string[] {
                            "1",
                            "First16To18EmployerIncentive (TT4)",
                            "FullyFundedSfa",
                            "500"});
#line 12
 testRunner.And("the funding source service generates the following contract type 2 payments:", ((string)(null)), table7, "And ");
#line hidden
#line 21
 testRunner.When("the period closes and month end processing begins", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 22
 testRunner.And("the funding source payments event are received", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "Delivery Period",
                            "TransactionType",
                            "FundingSource",
                            "Amount"});
                table8.AddRow(new string[] {
                            "1",
                            "Learning (TT1)",
                            "CoInvestedSfa",
                            "900"});
                table8.AddRow(new string[] {
                            "1",
                            "Completion (TT2)",
                            "CoInvestedSfa",
                            "2700"});
                table8.AddRow(new string[] {
                            "1",
                            "Balancing (TT3)",
                            "CoInvestedSfa",
                            "1800"});
                table8.AddRow(new string[] {
                            "1",
                            "Learning (TT1)",
                            "CoInvestedEmployer",
                            "100"});
                table8.AddRow(new string[] {
                            "1",
                            "Completion (TT2)",
                            "CoInvestedEmployer",
                            "300"});
                table8.AddRow(new string[] {
                            "1",
                            "Balancing (TT3)",
                            "CoInvestedEmployer",
                            "1350"});
                table8.AddRow(new string[] {
                            "1",
                            "First16To18EmployerIncentive (TT4)",
                            "FullyFundedSfa",
                            "500"});
#line 23
 testRunner.Then("the provider payments service will store the following payments:", ((string)(null)), table8, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
